const cont1=document.querySelector('.selec-1')
const cont2=document.querySelector('.selec-2')
//const cont3=document.querySelector('#3')
//const cont4=document.querySelector('#4')
//const cont5=document.querySelector('#5')
//const cont6=document.querySelector('#6')

const contenu1=document.querySelector('.contenu1')
const contenu2=document.querySelector('.contenu2')
//const contenu1=document.querySelector('.contenu1')
const toutContenu=document.querySelectorAll('.cont')
const hautAct=document.querySelector('.but1')
const haut=document.querySelector('.crit')
const menus=document.querySelector('.menus')
cont1.addEventListener('click',()=>{
    contenu2.classList.remove('active')
    cont2.classList.remove('active')
    contenu1.classList.add('active')
    cont1.classList.add('active')
})
cont2.addEventListener('click',()=>{
    contenu1.classList.remove('active')
    cont1.classList.remove('active')
    contenu2.classList.add('active')
    cont2.classList.add('active')
})
hautAct.addEventListener('click',()=>{
    haut.classList.toggle('activ')
})